// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Splash() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div id=\"splash\" class=\"fixed inset-0 bg-gray-900 flex justify-center items-center z-50 opacity-100 transition-all duration-500\"><img src=\"/assets/stati.png\" alt=\"\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = fadeOut().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}

func fadeOut() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_fadeOut_0af6`,
		Function: `function __templ_fadeOut_0af6(){setTimeout(()=>{
    document.querySelector("#splash").classList.add("opacity-0")
    setTimeout(()=>{
      document.querySelector("#splash").classList.add("hidden")
      document.querySelector("body").classList.remove("overflow-y-hidden")
    },500)
  },1500)
}`,
		Call:       templ.SafeScript(`__templ_fadeOut_0af6`),
		CallInline: templ.SafeScriptInline(`__templ_fadeOut_0af6`),
	}
}
